"""empty message

Revision ID: 3141a0e8545a
Revises: 97438523ec5b
Create Date: 2019-06-13 11:08:37.906973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3141a0e8545a'
down_revision = '97438523ec5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productfeedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('feedback_ID', sa.INTEGER(), server_default=sa.text(u'nextval(\'"feedback_feedback_ID_seq"\'::regclass)'), nullable=False),
    sa.Column('blog_ID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('user_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('user_comment', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_ID'], [u'blog_database.blog_ID'], name=u'feedback_blog_ID_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('feedback_ID', name=u'feedback_pkey')
    )
    op.create_table('productfeedback',
    sa.Column('feedback_ID', sa.INTEGER(), server_default=sa.text(u'nextval(\'"productfeedback_feedback_ID_seq"\'::regclass)'), nullable=False),
    sa.Column('product_ID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('user_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('user_comment', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_ID'], [u'product_database.product_ID'], name=u'productfeedback_product_ID_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('feedback_ID', name=u'productfeedback_pkey')
    )
    # ### end Alembic commands ###
