"""empty message

Revision ID: f0cc51977e0d
Revises: 
Create Date: 2019-07-22 17:17:20.304182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0cc51977e0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('gallery_ID', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('gallery_ID')
    )
    op.create_table('pages',
    sa.Column('page_ID', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=False),
    sa.Column('page_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('page_ID'),
    sa.UniqueConstraint('page_name')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('sale_ID', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('charge_id', sa.String(length=100), nullable=True),
    sa.Column('refunded', sa.Boolean(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('month', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('invoice', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_ID'], ['users.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sale_ID')
    )
    op.create_table('invoices',
    sa.Column('invoice_ID', sa.Integer(), nullable=False),
    sa.Column('sale_ID', sa.Integer(), nullable=True),
    sa.Column('event_ID', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sale_ID'], ['sales.sale_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_ID')
    )
    op.drop_table('cart')
    op.drop_column(u'events', 'taxable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'events', sa.Column('taxable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('cart',
    sa.Column('cart_ID', sa.INTEGER(), server_default=sa.text(u'nextval(\'"cart_cart_ID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_ID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_ID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_ID'], [u'events.event_ID'], name=u'cart_event_ID_fkey', ondelete=u'SET NULL'),
    sa.ForeignKeyConstraint(['user_ID'], [u'users.userID'], name=u'cart_user_ID_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('cart_ID', name=u'cart_pkey')
    )
    op.drop_table('invoices')
    op.drop_table('sales')
    op.drop_table('revoked_tokens')
    op.drop_table('pages')
    op.drop_table('gallery')
    # ### end Alembic commands ###
